"""Add cleaned_summary to infield_notes

Revision ID: 2293117d8716
Revises: d135490a5b5b
Create Date: 2025-05-15 10:36:32.094512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2293117d8716'
down_revision: Union[str, None] = 'd135490a5b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infield_notes', sa.Column('cleaned_summary', sa.Text(), nullable=True))
    op.add_column('infield_notes', sa.Column('participants', sa.Text(), nullable=True))
    op.add_column('infield_notes', sa.Column('visit_details', sa.Text(), nullable=True))
    op.add_column('infield_notes', sa.Column('visit_date', sa.Date(), nullable=True))
    op.alter_column('users', 'pay_tier',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'Tier 1'::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'pay_tier',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Tier 1'::text"))
    op.drop_column('infield_notes', 'visit_date')
    op.drop_column('infield_notes', 'visit_details')
    op.drop_column('infield_notes', 'participants')
    op.drop_column('infield_notes', 'cleaned_summary')
    # ### end Alembic commands ###
