"""add summary column to FormSubmission

Revision ID: 2d2daf0491fd
Revises: 2293117d8716
Create Date: 2025-05-15 23:48:32.088106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2daf0491fd'
down_revision: Union[str, None] = '2293117d8716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_submissions', sa.Column('service_date', sa.String(), nullable=True))
    op.add_column('form_submissions', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_submissions', 'summary')
    op.drop_column('form_submissions', 'service_date')
    # ### end Alembic commands ###
