"""Add cleaned_summary, participants, visit_details, visit_date to InfieldNote

Revision ID: 3716dd793735
Revises: 581a9e5d1e07
Create Date: 2025-05-15 02:26:18.074002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3716dd793735'
down_revision: Union[str, None] = '581a9e5d1e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
