"""Add client_number, participants, and miles to FormSubmission

Revision ID: 54e978ccdde7
Revises: b4cd4ae83990
Create Date: 2025-05-17 15:25:17.474156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54e978ccdde7'
down_revision: Union[str, None] = 'b4cd4ae83990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_submissions', sa.Column('client_number', sa.String(), nullable=True))
    op.add_column('form_submissions', sa.Column('participants', sa.Text(), nullable=True))
    op.add_column('form_submissions', sa.Column('miles', sa.String(), nullable=True))
    op.create_index(op.f('ix_form_submissions_client_number'), 'form_submissions', ['client_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_submissions_client_number'), table_name='form_submissions')
    op.drop_column('form_submissions', 'miles')
    op.drop_column('form_submissions', 'participants')
    op.drop_column('form_submissions', 'client_number')
    # ### end Alembic commands ###
