"""Add address, phone, participants to Client

Revision ID: 804f34f3329f
Revises: 54e978ccdde7
Create Date: 2025-05-18 11:42:00.690230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804f34f3329f'
down_revision: Union[str, None] = '54e978ccdde7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('address', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('participants', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'participants')
    op.drop_column('clients', 'phone_number')
    op.drop_column('clients', 'address')
    # ### end Alembic commands ###
