"""Add case_name, case_number, and context

Revision ID: 91da244d11ab
Revises: 
Create Date: 2025-05-10 11:38:03.709627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91da244d11ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_submissions', sa.Column('case_name', sa.String(), nullable=True))
    op.add_column('form_submissions', sa.Column('case_number', sa.String(), nullable=True))
    op.add_column('form_submissions', sa.Column('context', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_form_submissions_case_name'), 'form_submissions', ['case_name'], unique=False)
    op.create_index(op.f('ix_form_submissions_case_number'), 'form_submissions', ['case_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_submissions_case_number'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_case_name'), table_name='form_submissions')
    op.drop_column('form_submissions', 'context')
    op.drop_column('form_submissions', 'case_number')
    op.drop_column('form_submissions', 'case_name')
    # ### end Alembic commands ###
