"""Add case_worker and worker_email to Client

Revision ID: b4cd4ae83990
Revises: 2d2daf0491fd
Create Date: 2025-05-17 14:47:29.565627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4cd4ae83990'
down_revision: Union[str, None] = '2d2daf0491fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('case_worker', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('worker_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'worker_email')
    op.drop_column('clients', 'case_worker')
    # ### end Alembic commands ###
